### ISSUE TITLE
curly braces are inescapable

### ISSUE THREAD

**Issue by masukomi** [raku-community-modules/Template6#21] opened 2022-11-29 23:14 UTC
if you have a template with `{ foo }` or `{{ foo }}` in it, Template6 will "blow chunks". There is no number of backslashes that will successfully escape them. 

using the test harness below we get this output:

```
❯ raku minit6test.rakumod
with initial space
 {{ foo }}

without initial space
===SORRY!=== Error while compiling /Users/masukomi/workspace/temp/EVAL_1
Starter {{{{{{ is immediately followed by a combining codepoint. Please use { without a combining glyph ({{{{{{ was at line 4)
at /Users/masukomi/workspace/temp/EVAL_1:7
------> }⏏<EOL>
    expecting any of:
        }}}}}}
```

note that in real world testing i've found that the the offending `{` doesn't have to be the first thing in the template file. I can't explain why, in this test harness adding space before it (on the line or on preceeding lines, seems to fix things.

-----
test harness courtesy of  @dakkar

```
use v6.d;
use Template6;

my Template6 $t .= new();

say "with initial space";
$t.add-template('good_test',q:to<END>);
 {{ foo }}
END

say $t.process('good_test');

say "without initial space";
$t.add-template('bad_test',q:to<END>);
{{ foo }}
END

say $t.process('bad_test');


```

**Comment by 2colours** [comment] 2022-12-05 20:14
I'm planning to take up on this module... well, soon-ish. Probably in two weeks. Sadly, documentation for it is very ad-hoc, if present at all.

**Comment by raiph** [comment] 2022-12-07 01:08
cf [in an SO answer I wrote](https://stackoverflow.com/questions/54937834/a-perl-6-regex-to-match-a-perl-6-delimited-comment#:~:text=This%20doesn%27t%20look,is%20to%20me.)):

> This doesn't look directly relevant to your question but I encountered it when trying to understand the nested delimiter rules.
>
> So when I got to this part of my answer I started by searching the Rakudo repo for "immediately followed". That led to a [fail-terminator method](https://github.com/rakudo/rakudo/blob/8095ceada8bbfb7f2840bd386f8810f81a85687c/src/Perl6/Grammar.nqp#L219-L237) in the Raku grammar.

**Comment by 2colours** [comment] 2023-03-20 11:05
@masukomi congratulations, [you successfully injected a syntax error into the string escaping](https://github.com/raku-community-modules/Template6/blob/e259e083c1d85702c3ddd94e36c82a351acf2c7e/lib/Template6/Parser.rakumod#L222) . :) This kind of quoting absolutely doesn't care about backslashes, from what I know, so no surprise it didn't help. However, I can confirm that adding the spaces should at the very least change the situation.

```raku
use v6.*;
my $string = ' {{{foo}}} ';
q[Q{{{{\qq[$string]}}}}].snitch.EVAL.say;
# Q{{{{ {{{foo}}} }}}}
#  {{{foo}}} 
```

The first line will go to the script that needs to be eval'd, the second line is the output which should round-trip.

Now the thing is, escaping is an underrated problem if we want to cover all cases. I think, in theory, if we escape all backslashes and all apostrophes (or closing delimiter in general) in a q-string, we should be in the safe.  
There is something I would like to try first, though: heredoc Q-strings. Q-strings do not allow for any escaping - this is good because they cannot misinterpret the input, except for one way: when the closing delimiter appears, which will downright yield a syntax error. However, at the time we want to construct it, we have all the knowledge in the universe about the content, so we can just generate a delimiter that we know doesn't appear in the particular string, e.g ENDx, where x denotes the smallest positive integer for which 'ENDx' doesn't appear in the string. :P

**Comment by 2colours** [comment] 2023-03-20 15:12
Please try the new release. I integrated the "bad test" among other things. :)

**Closed by 2colours** 2023-03-20 15:12 UTC
